import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider"
import { GlobalHeader } from "@/components/global-header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App Boilerplate",
  description: "Generated by create next app",
  icons: [
    {
      url: "./favicon.ico",
      href: "/images/logo.svg",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className="bg-white dark:bg-black text-black dark:text-white min-h-screen">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <GlobalHeader />
            <div className="mx-auto w-full space-y-8 px-2 pt-20 lg:px-8 lg:py-8">
                <div className="rounded-lg p-3.5 lg:p-6">{children}</div>
            </div>
          </ThemeProvider>
      </body>
    </html>
  );
}
